#!/usr/bin/env python3
"""Regenerate src/font_data.zig from the X11 misc-fixed bitmap fonts (public domain).

Dev-time only: the Pis never run this. Needs Pillow and xfonts-base installed.
  usage: tools/genfont.py > src/font_data.zig && zig fmt src/font_data.zig
"""
import gzip, os, shutil, sys, tempfile
from PIL import Image, ImageDraw, ImageFont

SRC = "/usr/share/fonts/X11/misc"
FONTS = [("small", "5x8.pcf.gz", 5, 8), ("large", "10x20.pcf.gz", 10, 20)]
FIRST, LAST = 32, 126

def load(name, h):
    d = tempfile.mkdtemp()
    out = os.path.join(d, name[:-3])
    with gzip.open(os.path.join(SRC, name)) as f, open(out, "wb") as g:
        shutil.copyfileobj(f, g)
    return ImageFont.truetype(out, h)  # FreeType reads PCF; size selects the bitmap strike

def glyph(font, ch, w, h):
    im = Image.new("1", (w, h), 0)
    ImageDraw.Draw(im).text((0, 0), ch, font=font, fill=1)
    cols = []
    for x in range(w):
        v = 0
        for y in range(h):
            if im.getpixel((x, y)):
                v |= 1 << y
        cols.append(v)
    return cols

print("//! Generated by tools/genfont.py from the X11 misc-fixed fonts (public domain). Do not edit.")
print("//! Each glyph is `w` column words, bit 0 = top row, for ASCII %d..%d." % (FIRST, LAST))
print()
for key, fname, w, h in FONTS:
    font = load(fname, h)
    print("pub const %s = struct {" % key)
    print("    pub const w = %d;" % w)
    print("    pub const h = %d;" % h)
    print("    pub const data = [_][%d]u32{" % w)
    for c in range(FIRST, LAST + 1):
        cols = glyph(font, chr(c), w, h)
        print("        .{ %s }, // %s" % (", ".join("0x%X" % v for v in cols), repr(chr(c))[1:-1]))
    print("    };")
    print("};")
    print()
